architecture: YOLOv3
use_gpu: true
# 数据量 * epoch_size / GPU_num / batch_size
# 4926 * 120 / 4 / 4 => 36000
max_iters: 36000
log_smooth_window: 5
log_iter: 5
save_dir: output
snapshot_iter: 3000
metric: VOC
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar
weights: output/ppyolo_bank_human/model_final
num_classes: 3
use_fine_grained_loss: true
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  # anchors: [[10, 13], [16, 30], [33, 23],
  #           [30, 61], [62, 45], [59, 119],
  #           [116, 90], [156, 198], [373, 326]]
  anchors: [[22, 47], [29, 112], [41, 170],
            [75, 123], [62, 243], [106, 148],
            [101, 278], [121, 384], [155, 328]]
  norm_decay: 0.
  coord_conv: true
  iou_aware: true
  iou_aware_factor: 0.4
  scale_x_y: 1.05
  spp: true
  yolo_loss: YOLOv3Loss
  nms: MatrixNMS
  drop_block: true

YOLOv3Loss:
  ignore_thresh: 0.7
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

IouAwareLoss:
  loss_weight: 1.0
  max_height: 608
  max_width: 608

MatrixNMS:
    background_label: -1
    keep_top_k: 100
    normalized: false
    score_threshold: 0.01
    post_threshold: 0.01

LearningRate:
  # base_lr: 0.00333
  # 2 卡初始值 0.0025，nan 后除以 3
  base_lr: 0.001667
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 28800
    - 30000
  - !LinearWarmup
    start_factor: 0.
    steps: 2100

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'ppyolo_bank_human_reader.yml'
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset/bank
    anno_path: train.txt
    use_default_label: false
    with_background: false
  mixup_epoch: 350
  batch_size: 4

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/bank/
    anno_path: valid.txt
    use_default_label: false
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    dataset_dir: dataset/bank/
    anno_path: label_list.txt
    use_default_label: false
    with_background: false
